enum CategoryTypes {
  FITNESS
  FUEL
  PRODUCTIVITY
  SOCIAL
  REST
}

type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  userEmail: AWSEmail!
  userName: String!
  userPassword: String!
  userGoals: [Goal] @hasMany(indexName: "byUser", fields: ["id"])
}

type Goal @model @auth(rules: [{allow: public}]) {
  id: ID!
  goalStart: AWSDateTime!
  goalEnd: AWSDateTime
  goalCategory: CategoryTypes!
  goalCurrentDuration: DurationBeat!
  goalTargetDuration: DurationBeat!
  goalPercentage: Float
  userID: ID! @index(name: "byUser")
  goalOfUser: User! @belongsTo(fields: ["userID"])
  goalActivities: [Activity] @hasMany(indexName: "byGoal", fields: ["id"])
}

type Activity @model @auth(rules: [{allow: public}]) {
  id: ID!
  activityStart: AWSDateTime!
  activityEnd: AWSDateTime!
  activityCategory: CategoryTypes!
  activityDuration: DurationBeat!
  goalID: ID! @index(name: "byGoal")
  activityOfGoal: Goal! @belongsTo(fields: ["goalID"])
  activityMetrics: [Metric] @manyToMany(relationName: "ActivityMetric")
}

type Metric @model @auth(rules: [{allow: public}]) {
  id: ID!
  metricTimestamp: AWSDateTime!
  metricLocation: String
  activities: [Activity] @manyToMany(relationName: "ActivityMetric")
  metricHeartRate: Int
}

type DurationBeat {
  durationSeconds: Int
  durationMinutes: Int
  durationHours: Int
}